In [1]:
import torch as pt

In [2]:
Lst = []
for i in range(3):
    x = pt.rand(4)
    Lst.append(x)

In [3]:
Lst

[tensor([0.5502, 0.7152, 0.5576, 0.4335]),
 tensor([0.6489, 0.6588, 0.1749, 0.4834]),
 tensor([0.7335, 0.6073, 0.6380, 0.1670])]

In [4]:
x[0] = 6

In [5]:
Lst

[tensor([0.5502, 0.7152, 0.5576, 0.4335]),
 tensor([0.6489, 0.6588, 0.1749, 0.4834]),
 tensor([6.0000, 0.6073, 0.6380, 0.1670])]

In [25]:
x = pt.rand(10, 8, 3)

In [27]:
y = pt.rand(2).unsqueeze(1)
y_repeat = y.repeat_interleave(4, dim=0)
y_repeat

tensor([[0.2546],
        [0.2546],
        [0.2546],
        [0.2546],
        [0.0287],
        [0.0287],
        [0.0287],
        [0.0287]])

In [29]:
y_repeat.shape

torch.Size([8, 1])

In [30]:
x.shape

torch.Size([10, 8, 3])

In [33]:
xall = x + y_repeat

In [34]:
xall[0]

tensor([[1.2181, 0.4307, 0.9484],
        [0.2853, 0.4803, 0.6170],
        [1.1127, 0.5091, 0.5124],
        [0.9620, 0.9530, 0.6572],
        [0.8278, 0.4001, 0.0734],
        [0.6559, 0.1635, 0.8076],
        [0.1164, 0.8950, 0.6445],
        [0.7277, 0.9048, 0.8369]])

In [38]:
for i in range(10):
    assert pt.allclose(xall[i], x[i] + y_repeat)